### ISSUE TITLE
Some additional projects which could be added

### ISSUE THREAD

**Issue by heyyoyo** [alehkot/druphpet#11]
Get stats on memcache:
-------------------------------
http://code.google.com/p/phpmemcacheadmin/
The installation is really, I just added the directory inside /var/www/default

So script accessible via : 
http://192.168.9.10/memcache/

Get stats on PHP Opcache:
----------------------------
https://github.com/PeeHaa/OpCacheGUI

**Comment by alehkot** [comment]
@heyyoyo I like the ideas. The tools will be integrated.
