### ISSUE TITLE
Provision on reload to add new vhosts without wiping mysql?

### ISSUE THREAD

**Issue by kevinquillen** [alehkot/druphpet#17]
Is it possible to add new vhosts to config.yaml and have them added in on reload, without deleting all existing mysql databases? Currently, if I add a vhost and reprovision, it deletes the database and recreates it. This can be problematic if I want to work on a couple of sites at a time, and then have to add a new one.

**Comment by heyyoyo** [comment]
I added some vhosts to my config.yaml files with corresponding database. my databases are still there after provisioning.
1) vagrant up
2) config.yaml file modified (i adviced you to commit it to your git repository for future version of druphpet, and merge it with the new version. I did a couple of time, it works great)
3) vagrant provision -> my databases are still here
4) vagrant reload -> my databases are still here

**Comment by kevinquillen** [comment]
Yes, but did you try 

```
vagrant reload --provision
```

Or should I use vagrant provision? I found that the command above wiped the data in the defined MySQL databases in config.yaml.

**Comment by heyyoyo** [comment]
I already tried this command previously, never get that behavior.
Maybe it's permissions issues on the database, did you change mysql users ?

**Comment by kevinquillen** [comment]
Resolved

**Comment by heyyoyo** [comment]
What was the problem ?

**Comment by kevinquillen** [comment]
I may have been mistaken and looking at the wrong database when it reloaded - which always had nothing.

I can add as many as I want now and 'vagrant provision' works just fine.

**Comment by heyyoyo** [comment]
Good to know.
