### ISSUE TITLE
PHP with MYSQL Asynchronous

### ISSUE THREAD

**Issue by heyyoyo** [alehkot/druphpet#18]
I added the package php5-mysqlnd 

Like this I could use the awesome module(not finished) "Asynchronous Prefetch Database Query Cache" of  mikeytown2.

Could we change druphpet to make it default ?

**Comment by alehkot** [comment]
@heyyoyo It's already here. 
![screenshot](http://s17.postimg.org/ahid1lqfj/2015_02_28_17_26_51.png)

**Comment by heyyoyo** [comment]
Strange I had to install it, maybe it has been added in new puphpet recently, and my re-provision didn't work nicely.

**Comment by heyyoyo** [comment]
I have just installed the last druphpet and again I had to reinstall php5-mysqlnd.
It's really strange if I check if the package php5-mysqlnd is present, with the command:
dpkg -l |grep mysqlnd

But in PHP info I dont' see it loaded.
Even in the php extensions directory(/usr/lib/php5/20131226) I don't see the mysqlnd.so file.

After sudo apt-get install php5-mysqlnd, everything work again.

here is the results:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  php5-mysql
The following NEW packages will be installed:
  php5-mysqlnd
0 upgraded, 1 newly installed, 1 to remove and 110 not upgraded.
Need to get 0 B/138 kB of archives.
After this operation, 260 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 75869 files and directories currently installed.)
Removing php5-mysql (5.6.6+dfsg-1+deb.sury.org~trusty+1) ...
php5_invoke prerm: Disable module mysql for cli SAPI
php5_invoke prerm: Disable module mysql for apache2 SAPI
php5_invoke prerm: Disable module mysqli for cli SAPI
php5_invoke prerm: Disable module mysqli for apache2 SAPI
php5_invoke prerm: Disable module pdo_mysql for cli SAPI
php5_invoke prerm: Disable module pdo_mysql for apache2 SAPI
Processing triggers for libapache2-mod-php5 (5.6.6+dfsg-1+deb.sury.org~trusty+1) ...
Selecting previously unselected package php5-mysqlnd.
(Reading database ... 75858 files and directories currently installed.)
Preparing to unpack .../php5-mysqlnd_5.6.6+dfsg-1+deb.sury.org~trusty+1_amd64.deb ...
Unpacking php5-mysqlnd (5.6.6+dfsg-1+deb.sury.org~trusty+1) ...
Processing triggers for libapache2-mod-php5 (5.6.6+dfsg-1+deb.sury.org~trusty+1) ...
Setting up php5-mysqlnd (5.6.6+dfsg-1+deb.sury.org~trusty+1) ...
php5_invoke: Enable module mysqlnd for cli SAPI
php5_invoke: Enable module mysqlnd for apache2 SAPI
php5_invoke: Enable module mysql for cli SAPI
php5_invoke: Enable module mysql for apache2 SAPI
php5_invoke: Enable module mysqli for cli SAPI
php5_invoke: Enable module mysqli for apache2 SAPI
php5_invoke: Enable module pdo_mysql for cli SAPI
php5_invoke: Enable module pdo_mysql for apache2 SAPI
Processing triggers for libapache2-mod-php5 (5.6.6+dfsg-1+deb.sury.org~trusty+1) ...
```

**Comment by heyyoyo** [comment]
I undertstand why, even if in config.yaml there is the line to install php5-mysqlnd extension, there is an explicit dependencies in phpmyadmin to 'php5-mysql'

in file \phpmyadmin\manifests\dependencies.pp:
```
class phpmyadmin::dependencies
{
    if $osfamily != 'Debian' {
        fail("Unsupported platform: ${osfamily}/${operatingsystem}")
    }
    require wget
    phpmyadmin::secure::install {['php5', 'php5-mysql','php5-mcrypt']:}
}
```
And installing this dependencies remove the extension 'php5-mysqlnd'

**Comment by heyyoyo** [comment]
The module "Asynchronous Prefetch Database Query Cache" of mikeytown2 
https://www.drupal.org/project/apdqc 
recommends 2 more settings for mysql:
'query_cache_type': '0'
'innodb_flush_log_at_trx_commit': '2'

**Comment by alehkot** [comment]
To update to the latest version please remove old modules from 'puphpet\puppet\modules' except .gitkeep and execute `vagrant reload --provision`.
