### ISSUE TITLE
Default MySQL max_allowed_packet to 128M?

### ISSUE THREAD

**Issue by kevinquillen** [alehkot/druphpet#19]
Is there a way to default this value from the config.yaml? I've found issues with the default being at 16M out of the box that requires it to be 128M - or Drupal 7 installation can tend to get stuck in a loop.

**Comment by kevinquillen** [comment]
Nevermind, got it!

**Comment by heyyoyo** [comment]
I agree that it should be increased by default. 
Maybe other values should de modified too like innodb_buffer_pool_size which should be set to 80% of available ram or 160% of database size.
