### ISSUE TITLE
Drupal 7 installation screen loops over and over

### ISSUE THREAD

**Issue by kevinquillen** [alehkot/druphpet#20]
I have a very weird and annoying issue when installing Drupal 7 on a Windows host as well as OSX host - I have replicated this issue in many browsers.

When Drupal gets to the database authentication screen, it will loop over and over. The only way around this is:

* Specify 128M in max_allowed_packet in MySQL configuration
* Specify BOTH $base_url and $cookie_domain in default.settings.php BEFORE Drupal copies it to make settings.php
* Specify the IP of the VM for the database connection instead of 'localhost' or the actual hostname

It can make installation very difficult because when it gets in a loop, even if you somehow get past it, you will be missing half of your database tables.

The firewall is off in both Windows and Mac.

What could be causing this? [I have used other Vagrant stacks without seeing this happen before](https://github.com/hashbangcode/vlad). Is there a simple config missing from Apache that could be causing this? Is opcode/APC caching on when it should not be (I disabled it in the yaml)?

I would like to not have to specify base url, cookie domain, or IP in the install process because it affects the settings.php file, and between developers, I do not want any inconsistencies (some may have different VM IPs, etc).

**Comment by heyyoyo** [comment]
I got this error too, and I didn't find the cause, but for me a simple F5 after saving database credentials bring me to next blue progress bar. But apparently it's or APC/Opcache issue or permissions issue:
https://www.drupal.org/node/749264
https://www.drupal.org/node/1800094

**Comment by kevinquillen** [comment]
Is there a way we can fix this in the build so it isn't a burden on the user?

**Comment by kevinquillen** [comment]
I am thinking it is more caching related and not file permissions. settings.php writes just fine and doesn't go to read only mode until you get past the installation.

**Comment by alehkot** [comment]
@kevinquillen @heyyoyo I have the same issue. In the latest version I had to disable APCu extension entirely (https://github.com/alehkot/druphpet/blob/master/puphpet/config.yaml) to fix it, because, unfortunately, I don't know the solution yet.

**Comment by kevinquillen** [comment]
I also have it disabled, still occurs:

https://github.com/kevinquillen/puppet-conf/blob/master/config-win.yaml

**Comment by alehkot** [comment]
@kevinquillen @heyyoyo Hi, could you please validate is the issue is gone?

**Comment by heyyoyo** [comment]
I confirm that the last commit fixed this drupal loop installation issue.
