### ISSUE TITLE
Error: concat(): Requires array to work

### ISSUE THREAD

**Issue by heyyoyo** [alehkot/druphpet#24]
I wanted to use compass lately, but even if it's was enabled in config.yaml, it wasn't installed properly.

So I decided to rerun vagrant reload --provision, but I got this error:

==> default: Error: concat(): Requires array to work with at /tmp/vagrant-puppet/modules-1b5381b6
cb85218ab56528bd372590ba/puphpet/manifests/ruby/install.pp:21 on node packer-virtualbox-iso-1422601639

I also tried to remove all modules, and  to syncronize them again, but I got the same error.

Is Compass working for you guys ?

**Comment by heyyoyo** [comment]
I found this issue:
https://github.com/maestrodev/puppet-rvm/issues/71

**Comment by alehkot** [comment]
@heyyoyo I have just fixed the issue in https://github.com/puphpet/puppet-puphpet fork, see https://github.com/alehkot/puppet-puphpet/commit/11d6cb7f4edd8e40c3cc79f52eb0a05e0321a8f0.
Please remove all modules, resync them again and execute `vagrant reload --provision` once more.

**Comment by heyyoyo** [comment]
You're fast man !
Thanks

**Comment by heyyoyo** [comment]
Hum now there is another error 
Error: Unknown function merge_yaml at /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/apache.pp:1 on node packer-virtualbox-iso-1422601639
