### ISSUE TITLE
Check websites on mobile ?

### ISSUE THREAD

**Issue by heyyoyo** [alehkot/druphpet#26]
I have no clue on how to check websites on mobiles ?
Except the simulator included on Chrome, is there a way to check websites done inside druphpet on our mobiles ?

**Comment by heyyoyo** [comment]
I have found to different ways to do it, but still didn't get success with them:

First idea, is to use a public_network with vagrant, like this my phone and the VM will be on the same network, and I will be able to browse the IP from the VM in my phone.

But there are 2 problems with this method:
* the public_network is stil not yet supported in puphpet but could be handled inside Vagrantfile:
https://github.com/puphpet/puphpet/issues/874
https://github.com/puphpet/puphpet/issues/1296

* Vagrant WINNFS for Windows supports only private_network mode
https://github.com/GM-Alex/vagrant-winnfsd

Second idea is to share my wifi card, inside windows, and then Bridge this virtual wifi connection with the one form VirtualBox:
I successfully created yet a virtual wifi connection, and my telephone could connect to it.
But I'm stucked on the bridge part.
I found a documentation here:
http://www.sebcharrot.com/blog/tag/virtualbox

Vagrant supports a bridge option, for the public network but I don't think it's possible for private_network.

**Comment by alehkot** [comment]
@heyyoyo If you have firewall enabled, you can create a tunnel to your host, just execute (e.g. on Windows in Git bash):
`ssh -L 8888:127.0.0.1:80 vagrant@druphpet.dev -N

Then you can access your host machine from mobile device using host machine's IP address, e.g.
http://169.254.40.240:8888/

It points to the default Apache location, but you can update your httpd.conf.

**Comment by heyyoyo** [comment]
Thanks alehkot it works great, 
I just had to add "-g" to make it work.

And regarding to my virtualhost, I just added an aditionnal port declaration, like this I could access the website by port or by domain from my desktop. Not sure that we can define this into config.yaml

    Listen 8080
    <VirtualHost *:8080 *:80>
      ServerName mydomain.com

**Comment by alehkot** [comment]
Hi again,

I have just found one very useful command: http://www.vagrantup.com/blog/feature-preview-vagrant-1-5-share.html. With `vagrant share` command you can easily expose your local env to the Internet.
