### ISSUE TITLE
Postgres settings not respected

### ISSUE THREAD

**Issue by kevinquillen** [alehkot/druphpet#29]
Under the server settings, I set the listen_addresses: '*' option. When I ssh into the server, this line in postgresql.conf is commented out meaning it is using localhost as the default. This means that it is not listening for connections coming from outside of the VM.

I also had to add a custom rule to pg_hba.conf to allow logins from users on 0.0.0.0 with the trust directive.

Without these changes it was impossible to connect externally via pgAdmin or db viewer tools.

**Comment by alehkot** [comment]
Should be fixed now.
