### ISSUE TITLE
Nginx installation

### ISSUE THREAD

**Issue by heyyoyo** [alehkot/druphpet#7]
I'm interested in using Drupal with NGinx and I need some clarifications on its configuration instead of Apache.

Except disabling Apache and enabling Nginx, and disabling mod_php to use php-fpm instead.
Do I need to change anything else ?

There is apparently 2 configurations of Nginx for Drupal:

By NGinx community:
http://wiki.nginx.org/Drupal 

By Drupal community more advanced:
https://github.com/perusio/drupal-with-nginx \

Are those settings included ?

If I used NGinx instead of Apache will I be able to still use XDebug & XHprof ?
Is there any other incompatibilities ?

Any experience with Nginx is really welcome !

**Comment by alehkot** [comment]
@heyyoyo No, you don't need to change anything else. I have just created special 'nginx' branch with defaults and updated README.md with information about incompatible Druphpet modules with Nginx (at this moment they are Phpmyadmin, Webgrind, Pimpmylog, but it's just a matter of time before they become compatible).

Xdebug & Xhprof are still compatible. 

Regarding 2 configurations of Nginx for Drupal you mentioned, these settings haven't been included, but rewrite rules (nice urls) work. Gzip compression is enabled as well.

After initial provisioning you can `vagrant ssh` into your VM and go to /etc/nginx and play with Nginx settings.

Default config is the following:
`server {
  listen                *:80;

  server_name           druphpet.dev www.druphpet.dev;
  client_max_body_size 5m;

    index  index.html index.htm index.php;

  access_log            /var/log/nginx/druphpet.dev.access.log;
  error_log             /var/log/nginx/druphpet.dev.error.log;

  location ~ \.php$ {

    root  /var/www/druphpet.dev;
    try_files $uri $uri/ /index.php /index.php$is_args$args$is_args$args;
    index  index.html index.htm index.php;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $request_filename;
    fastcgi_param APP_ENV dev;
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    include fastcgi_params;
  }
  location / {

    root  /var/www/druphpet.dev;
    try_files $uri $uri/ index.php /index.php$is_args$args;
  }
  sendfile off;
}`

**Comment by heyyoyo** [comment]
Awesome work, thanks a lot for your contribution.

**Comment by heyyoyo** [comment]
Regarding PHP settings:
If PHP 5.6 is used so there is no need to add those APC settings:
apc.shm_size: '128M'
apc.ttl: '0'
apc.gc_ttl: '600'
apc.enable_cli: '1'
apc.mmap_file_mask: '/tmp/apc.XXXXXX'

But instead those for Opcache:
http://stackoverflow.com/questions/17224798/how-to-use-php-opcache

; Sets how much memory to use
opcache.memory_consumption=128

;Sets how much memory should be used by OPcache for storing internal strings 
;(e.g. classnames and the files they are contained in)
opcache.interned_strings_buffer=8

; The maximum number of files OPcache will cache
opcache.max_accelerated_files=4000

;How often (in seconds) to check file timestamps for changes to the shared
;memory storage allocation.
opcache.revalidate_freq=60

;If enabled, a fast shutdown sequence is used for the accelerated code
;The fast shutdown sequence doesn't free each allocated block, but lets
;the Zend Engine Memory Manager do the work.
opcache.fast_shutdown=1

;Enables the OPcache for the CLI version of PHP.
opcache.enable_cli=1
If you use any library or code that uses code annotations you must enable save comments:

opcache.save_comments=1
